### ISSUE TITLE
[BUG]__main__:task:531 - Failed to connect to websocket

### ISSUE THREAD

**Issue by n-OlegS** [rdeepak2002/reddit-place-script-2022#290] opened 2022-04-03 18:04 UTC
![image](https://user-images.githubusercontent.com/95242220/161441737-938fdc75-6fc9-4200-ae99-b7d7b9e054f8.png)

**Comment by rdeepak2002** [comment] 2022-04-03 18:07
Closing this issue since it is a duplicate of https://github.com/rdeepak2002/reddit-place-script-2022/issues/280

**Closed by rdeepak2002** 2022-04-03 18:07 UTC
Labels: bug
