### ISSUE TITLE
placing pixels on already correct pixels

### ISSUE THREAD

**Issue by Covkie** [rdeepak2002/reddit-place-script-2022#90] opened 2022-04-02 18:44 UTC
tittle :3

**Comment by DeltaNeverUsed** [comment] 2022-04-02 18:47
This is probably caused by multithreading

it's probably trying to place two pixels down with in a second of each other so they both threads have the same board image

**Comment by Dmalikhammer4** [comment] 2022-04-02 18:48
Quick question guys, do we have to use the pixelated image?

**Comment by rdeepak2002** [comment] 2022-04-03 00:17
@Dmalikhammer4 

Yes, our algorithm does not pixelate the input image. It simply directly draws it pixel by pixel onto the r/place canvas.

**Comment by Dmalikhammer4** [comment] 2022-04-03 00:25
> @Dmalikhammer4
> 
> Yes, our algorithm does not pixelate the input image. It simply directly draws it pixel by pixel onto the r/place canvas.

Gotcha thank you so much. You guys did a lot of good work here, a couple of people on my sub were able to get it to work. I unfortunately was not, it was too overwhelming for me. I got to the docker part but there was problems with my python and the pillow package and I couldn't get it to run. Luckily one of the other guys was able to put my account down in their worker arrays.

**Comment by rdeepak2002** [comment] 2022-04-03 00:36
Ah I see. No problem!

**Comment by benjagr** [comment] 2022-04-03 02:39
Problem came back up since expansion... right half of place is not visible for Image comparator

**Comment by Plantchant** [comment] 2022-04-03 07:54
Fixed now. Please use new script and it is recommended to put 3 seconds in between your accounts (thread_delay).

**Closed by Plantchant** 2022-04-03 07:54 UTC
