### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by neeamradia** [rdeepak2002/reddit-place-script-2022#264] opened 2022-04-03 14:48 UTC
# Bug Report Form

## Checklist

- [/ ] I am using the latest version of the code.
- [/ ] I am absolutely sure I read the README in its entirety.
- [/ ] I have made sure this is not a duplicate issue.
- [ /] I have filled out this form correctly.

`2022-04-03 15:47:08.302 | INFO     | __main__:load_image:148 - Loaded image size: (920, 570)
Authorization successful!
Obtaining access token...
Authorization failed!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\neeam\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\neeam\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\neeam\Desktop\reddit-place-script-2022\main.py", line 586, in task
    current_r, current_c, new_rgb = self.get_unset_pixel(
  File "C:\Users\neeam\Desktop\reddit-place-script-2022\main.py", line 405, in get_unset_pixel
    new_rgb = self.closest_color(target_rgb)
  File "C:\Users\neeam\Desktop\reddit-place-script-2022\main.py", line 105, in closest_color
    r, g, b = target_rgb[:3]
TypeError: 'int' object is not subscriptable
`

**Comment by ixi2101** [comment] 2022-04-03 14:51
Duplicate of #258

**Closed** 2022-04-03 14:52 UTC
Labels: bug
