### ISSUE TITLE
630.0 seconds until next pixel is drawn

### ISSUE THREAD

**Issue by AggelosM** [rdeepak2002/reddit-place-script-2022#55] opened 2022-04-02 11:51 UTC
Why 630? It should be 300 (or 305 to be safe).

In the browser, I get 5 minutes of cooldown, not 10.

**Comment by Adenser** [comment] 2022-04-02 13:04
The safe timer is 330 seconds, feels like multi-threading is somehow updating the value of time that should be counted twice with causes it go up to 700? Didn't tested with more than 2 accounts.

Hard code fix is to:
(optional: Go to 349 line, change the pixel_place_frequency value to smaller if you want, default is 330 seconds(305 is safe minimum))
go to 390 line, and leave it only with pixel_place_frequency. It will force to use only value from pixel_place_frequency, default is 330 seconds, can be changed (look optional)

**REMEMBER THAT ONLY VERIFIED ACCOUNTS HAVE 5 MINUTE COOLDOWN. IF NOT VERIFIED COOLDOWN MIGHT GO UP TO 20 MINUTES**

**Comment by chipqs** [comment] 2022-04-02 13:25
> The safe timer is 330 seconds, feels like multi-threading is somehow updating the value of time that should be counted twice with causes it go up to 700? Didn't tested with more than 2 accounts.
> 
> Hard code fix is to: (optional: Go to 349 line, change the pixel_place_frequency value to smaller if you want, default is 330 seconds(305 is safe minimum)) go to 390 line, and leave it only with pixel_place_frequency. It will force to use only value from pixel_place_frequency, default is 330 seconds, can be changed (look optional)
> 
> **REMEMBER THAT ONLY VERIFIED ACCOUNTS HAVE 5 MINUTE COOLDOWN. IF NOT VERIFIED COOLDOWN MIGHT GO UP TO 20 MINUTES**

Could you tell us what the line was (what it contained) or the new line location since theres been an update

**Comment by AggelosM** [comment] 2022-04-02 13:26
I think they say that the line with
`last_time_placed_pixel + pixel_place_frequency - current_timestamp`
must change to
`pixel_place_frequency`

**Comment by AggelosM** [comment] 2022-04-02 13:53
> I think they say that the line with `last_time_placed_pixel + pixel_place_frequency - current_timestamp` must change to `pixel_place_frequency`

This breaks something though. The script doesn't repeat.

**Comment by jack93885** [comment] 2022-04-02 14:30
I have had success halving the pixel_place_frequency to 165. seems to output a 330 second wait for me

**Comment by gemcdaniel** [comment] 2022-04-02 16:54
The problem is the `set_pixel_and_check_ratelimit` returns the next time a pixel can be placed but is being assigned to the variable `last_time_placed_pixel` which is used to calculate the `time_until_next_draw` by `last_time_placed_pixel + pixel_place_frequency - current_timestamp` which ends up with double the wait time. The `time_until_next_draw` should simply be `last_time_placed_pixel - current_timestamp`. Obviously `last_time_placed_pixel` should be renamed.

**Comment by gemcdaniel** [comment] 2022-04-02 17:18
This should now be fixed with my recent pull request merged in

**Closed** 2022-04-02 17:19 UTC
Labels: bug
