### ISSUE TITLE
Failed to connect to websocket

### ISSUE THREAD

**Issue by jonnyswboy** [rdeepak2002/reddit-place-script-2022#371] opened 2022-04-04 02:24 UTC
```
2022-04-03 22:23:17.443 | ERROR    | __main__:task:492 - Failed to connect to websocket, trying again in 30 seconds...

2022-04-03 22:23:16.213 | INFO     | src.proxy:Init:78 - successfully connected to tor!
2022-04-03 22:23:16.221 | INFO     | src.utils:load_image:35 - Converted to rgba
2022-04-03 22:23:16.222 | INFO     | src.utils:load_image:38 - Loaded image size: (15, 9)
Apr 03 22:23:17.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
Apr 03 22:23:17.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
2022-04-03 22:23:17.443 | ERROR    | __main__:task:492 - Failed to connect to websocket, trying again in 30 seconds...
Apr 03 22:23:17.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
Apr 03 22:23:17.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
Apr 03 22:23:17.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
Apr 03 22:23:17.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
Apr 03 22:23:17.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
Apr 03 22:23:18.000 [notice] Bootstrapped 100% (done): Done
2022-04-03 22:23:25.384 | ERROR    | __main__:task:492 - Failed to connect to websocket, trying again in 30 seconds...
2022-04-03 22:23:33.413 | ERROR    | __main__:task:492 - Failed to connect to websocket, trying again in 30 seconds...
2022-04-03 22:23:41.386 | ERROR    | __main__:task:492 - Failed to connect to websocket, trying again in 30 seconds...
2022-04-03 22:23:47.614 | ERROR    | __main__:task:492 - Failed to connect to websocket, trying again in 30 seconds...
```

**Comment by TheForgottenKing** [comment] 2022-04-04 02:28
dup of 368

**Comment by bjb28** [comment] 2022-04-04 02:32
Duplicate of #368

**Closed** 2022-04-04 02:32 UTC
Labels: bug
