### ISSUE TITLE
[BUG] Transparent pixel in PNG is throwing and error

### ISSUE THREAD

**Issue by RedHarvester** [rdeepak2002/reddit-place-script-2022#324] opened 2022-04-03 21:06 UTC
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [did my best] I have made sure this is not a duplicate issue.
- [der; did my best] I have filled out this form correctly.

## Describe the bug

When a PNG has a transparent pixel, I am getting the following error and the thread dies.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Documents\GitHub\reddit-place-script-2022\main.py", line 701, in task
    pixel_color_index = ColorMapper.COLOR_MAP[new_rgb_hex]
KeyError: '#452A00'

## To Reproduce

Create a PNG with transparent pixels in it.

Steps to trigger the bug:

1. Attempt to use a transparent pixel within a PNG. 
2. Wait for placement of the transparent pixel
3. See error

## Expected behavior

Previous versions noted the transparent pixel was detected and moved to the next pixel.

## Additional context

None

**Comment by lithium720** [comment] 2022-04-03 21:09
Duplicate of #307 
Fix proposed in #319

**Closed** 2022-04-03 21:23 UTC
Labels: bug, duplicate
