### ISSUE TITLE
[???] error: 'Y' has to be within 0-999 range

### ISSUE THREAD

**Issue by PopcornPlant** [rdeepak2002/reddit-place-script-2022#299] opened 2022-04-03 19:19 UTC
Anything else have this issue or is it just me?

**Comment by Risewill23** [comment] 2022-04-03 19:20
Only the first part of the board works for now

**Comment by ciherrera20** [comment] 2022-04-03 19:22
> 

Is there a simple fix? I tried just changing the numbers 1000 and 999 to 2000 and 1999 but I keep getting an index out of range error, so I'm assuming there's some more that needs to be done.

**Comment by Ferotiq** [comment] 2022-04-03 19:23
> Is there a simple fix? I tried just changing the numbers 1000 and 999 to 2000 and 1999 but I keep getting an index out of range error, so I'm assuming there's some more that needs to be done.

I think that's because the way the board image is captured is not up to date with the size of it. So the image is still 1kx1k

**Comment by Risewill23** [comment] 2022-04-03 19:24
> Is there a simple fix? I tried just changing the numbers 1000 and 999 to 2000 and 1999 but I keep getting an index out of range error, so I'm assuming there's some more that needs to be done.

Not really because the board are split up into 4 image

**Comment by PopcornPlant** [comment] 2022-04-03 19:29
I did a fix. Has anyone else done it or should I merge

**Comment by nekiwo** [comment] 2022-04-03 19:35
please tell what you did to fix it

**Comment by Risewill23** [comment] 2022-04-03 19:36
There is someone in pull requests that tried to fix it but I haven't tested because all of my alts got ratelimited banned for 15 years

**Comment by kagenokurei** [comment] 2022-04-03 19:45
Still not fixed even with dynamic canvas

**Comment by CAS-14** [comment] 2022-04-03 19:55
> I did a fix. Has anyone else done it or should I merge

Can you share your fix?

**Comment by CAS-14** [comment] 2022-04-03 20:13
> Still not fixed even with dynamic canvas

Yep. It isn't working for me either.

**Comment by PopcornPlant** [comment] 2022-04-03 20:18
Sorry I had a work call. I'll submit the thingy

**Comment by CAS-14** [comment] 2022-04-03 20:18
> Sorry I had a work call. I'll submit the thingy

Awesome, thank you!

**Comment by PopcornPlant** [comment] 2022-04-03 20:30
It's in pull requests @ contributors. I can't test it myself right now so someone do that before pushing it. I hate doing this mobility

**Comment by thoroc** [comment] 2022-04-03 23:06
Was the PR merged? Had is fixed the issue?

**Comment by josephdong1000** [comment] 2022-04-03 23:34
@thoroc just confirmed it works

**Comment by Skyline-9** [comment] 2022-04-04 23:26
Bug Fixed

**Closed by Skyline-9** 2022-04-04 23:26 UTC
Labels: bug, duplicate
