### ISSUE TITLE
[BUG] Only first 1000x1000 pixels of the board are loaded

### ISSUE THREAD

**Issue by ry-dgel** [rdeepak2002/reddit-place-script-2022#167] opened 2022-04-02 23:50 UTC
# Bug Report Form

## Checklist

- [ X] I am using the latest version of the code.
- [X ] I am absolutely sure I read the README in its entirety.
- [ X] I have made sure this is not a duplicate issue.
- [X ] I have filled out this form correctly.

## Describe the bug
I added a line to save the image that that is being pulled, and the right half is completely blank. This also explains why pixels outside of the 1000x1000 square are being immediately placed without proper checking. 

This image corresponds to the output of  the `get_board` function.
![board](https://user-images.githubusercontent.com/14968322/161405261-1e68dbd4-4676-43c1-bae1-785b3b00cb86.png)

**Comment by Phyronian** [comment] 2022-04-03 00:06
I found a work-around for the moment.
The script is receiving both sections of the board, however the id check at line 278 is removing the second section because both have the same id (I don't know why this is).
Bypassing this check results in the full image being processed and saved:
![board](https://user-images.githubusercontent.com/59706828/161405620-cd46df97-8b19-406e-9b22-c03a23b926ca.png)

**Comment by Skyline-9** [comment] 2022-04-03 01:43
Duplicate of #73

**Closed by Skyline-9** 2022-04-03 01:43 UTC
Labels: bug, duplicate
