### ISSUE TITLE
[BUG] `get_unset_pixel` not working correctly.

### ISSUE THREAD

**Issue by bjb28** [rdeepak2002/reddit-place-script-2022#176] opened 2022-04-03 02:44 UTC
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [x] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

I have noticed that it does not seem like the comparison of colors is taking place. The color from `pix2` is always returning (0,0,0) during my tests. I am still working to debug this more but wanted to share in hopes someone might have seen this.

## To Reproduce

To reproduce this run the script to replace an image that will match the pixel. The color being checked from the board is always (0,0,0)

## Expected behavior

The value from `pix2` should change to the correct color from the board image. 

## Additional context

Continue to debug and look at the board image to determine if there might be a problem with what is getting returned. I suspect the problem is someplace within lines 319-347 or in the `get_board` function.

**Comment by xDaHuaba** [comment] 2022-04-03 03:04
I think the problem is around the `get_board` function. 
At least on my side, it appears that I only get the left canvas side returned. In Lines 248-291 we expect to receive two images and them to be appended to the `imgs` list. But checking the `new_img` at the end of the `get_board` function (for example when adding the line `new_img.show()`) only shows one.
I am still far too new to web sockets to understand really what's happening here.

**Comment by xDaHuaba** [comment] 2022-04-03 03:19
On second look. I think I found the issue. The collection `already_added` on line 247 should be moved just before the `while True` loop on line 273. Need to test if this does not break anything, but seems promising.

**Comment by bjb28** [comment] 2022-04-03 03:26
@xDaHuaba  great find! I think we are getting close. When I test moving the `already_added` inside the loop it only duplicates the left side of the image.

**Comment by bjb28** [comment] 2022-04-03 03:47
Got it! The problem looks to be with line 249 and the `for` loop.  The index needs to be 1 higher so that the `id` on line 253 hits both sides of the canvas. I did this without moving the `already_added` collection. I ran a test and it appears to work.

To fix this change line 249 to: `for i in range(1, image_sizex * image_sizey + 1):`

I will work up a PR for this shortly.

**Comment by jeffro256** [comment] 2022-04-03 06:56
I am also having this issue. The bot is basically useless because it can't tell an unset pixel apart from a set pixel

**Comment by Plantchant** [comment] 2022-04-03 08:02
Try again with the new script. I think it may be fixed. Let me know :)

**Comment by RomainL972** [comment] 2022-04-03 10:56
This should have been fixed by https://github.com/rdeepak2002/reddit-place-script-2022/pull/209

**Closed by RomainL972** 2022-04-03 10:56 UTC
Labels: bug
