### ISSUE TITLE
Error when running main: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)

### ISSUE THREAD

**Issue by n-OlegS** [rdeepak2002/reddit-place-script-2022#120] opened 2022-04-02 20:45 UTC
Whenever I try to start main.py I get the following error:

Exception in thread Thread-1 (task):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/oleg/Downloads/reddit-place-script-2022-main/main.py", line 436, in task
    self.get_board(self.access_tokens[index]),
  File "/Users/oleg/Downloads/reddit-place-script-2022-main/main.py", line 192, in get_board
    ws = create_connection(
  File "/Users/oleg/Library/Python/3.10/lib/python/site-packages/websocket/_core.py", line 601, in create_connection
    websock.connect(url, **options)
  File "/Users/oleg/Library/Python/3.10/lib/python/site-packages/websocket/_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/Users/oleg/Library/Python/3.10/lib/python/site-packages/websocket/_http.py", line 136, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/Users/oleg/Library/Python/3.10/lib/python/site-packages/websocket/_http.py", line 272, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/Users/oleg/Library/Python/3.10/lib/python/site-packages/websocket/_http.py", line 248, in _wrap_sni_socket
    return context.wrap_socket(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)

I have checked the config file multiple times, everything seems good.
How can I fix this?

-Cheers

**Comment by cdoyne** [comment] 2022-04-02 20:46
i had this aswell

**Comment by ixi2101** [comment] 2022-04-02 20:47
https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

**Comment by rdeepak2002** [comment] 2022-04-02 20:56
Closing this issue since it is a duplicate of https://github.com/rdeepak2002/reddit-place-script-2022/issues/100

**Closed by rdeepak2002** 2022-04-02 20:56 UTC
