### ISSUE TITLE
image index out of range

### ISSUE THREAD

**Issue by wael9999** [rdeepak2002/reddit-place-script-2022#260] opened 2022-04-03 14:27 UTC
Got image: https://hot-potato.reddit.com/media/canvas-images/1648995899143-0-f-66C1E88M.png
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Boss\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\Boss\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "d:\users\Downloads\New folder (41)\reddit-place-script-2022-main\New folder\reddit-place-script-2022-main\main.py", line 492, in task
    current_r, current_c, new_rgb = get_unset_pixel(
  File "d:\users\Downloads\New folder (41)\reddit-place-script-2022-main\New folder\reddit-place-script-2022-main\main.py", line 284, in get_unset_pixel
    if pix2[x + pixel_x_start, y + pixel_y_start] != new_rgb:
IndexError: image index out of range
Exception ignored in: <module 'threading' from 'C:\\Users\\Boss\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py'>
Traceback (most recent call last):
  File "C:\Users\Boss\AppData\Local\Programs\Python\Python39\lib\threading.py", line 1428, in _shutdown
    lock.acquire()
KeyboardInterrupt:

**Comment by wael9999** [comment] 2022-04-03 14:43
tried png and got this
 Traceback (most recent call last):
  File "C:\Users\Boss\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\Boss\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "d:\users\Downloads\New folder (41)\reddit-place-script-2022-main\New folder\reddit-place-script-2022-main\main.py", line 492, in task
    current_r, current_c, new_rgb = get_unset_pixel(
  File "d:\users\Downloads\New folder (41)\reddit-place-script-2022-main\New folder\reddit-place-script-2022-main\main.py", line 283, in get_unset_pixel
    new_rgb = closest_color(target_rgb, rgb_colors_array)
  File "d:\users\Downloads\New folder (41)\reddit-place-script-2022-main\New folder\reddit-place-script-2022-main\main.py", line 111, in closest_color
    r, g, b = target_rgb
ValueError: too many values to unpack (expected 3)

**Comment by ixi2101** [comment] 2022-04-03 14:46
Duplicate of #258

**Closed by ixi2101** 2022-04-03 14:46 UTC
Labels: bug
